### ISSUE TITLE
optional use of caproto

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#73]
Via the `iconfig` support, make it easy to switch the backend from [PyEpics](https://pyepics.github.io/pyepics/overview.html) to [caproto](https://caproto.github.io/caproto) by a setting in the `iconfig.yml` file.

See https://github.com/BCDA-APS/apstools/commit/191f5ddca6f308b04ec8f60bd349b3c14b01bb68

```py
import ophyd
ophyd.set_cl("caproto")
```

**Comment by prjemian** [comment]
Since caproto is noisier about duplicate PV servers:

```bash
export EPICS_CA_AUTO_ADDR_LIST="no"
export EPICS_CA_ADDR_LIST="127.0.0.1"
```

**Comment by prjemian** [comment]
Note that with caproto, **lots** of RuntimeErrors reported to console during normal `exit` from command line IPython session.  Here is _one_ of them

```bash
Removing <VirtualCircuitManager circuit=<VirtualCircuit host='192.168.144.97' port=40323 our_role=Role.CLIENT> logger_name='caproto.circ'> pvs=144 ioids=0 subscriptions=0> due to an internal error on receipt of new data: cannot schedule new futures after interpreter shutdown
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/site-packages/caproto/threading/client.py", line 270, in __call__
    if obj.received(bytes_recv, address) is ca.DISCONNECTED:
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/site-packages/caproto/threading/client.py", line 1338, in received
    self._process_command(c)
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/site-packages/caproto/threading/client.py", line 1440, in _process_command
    pv.access_rights_changed(command.access_rights)
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/site-packages/caproto/threading/client.py", line 1628, in access_rights_changed
    self.access_rights_callback.process(self, rights)
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/site-packages/caproto/threading/client.py", line 2046, in process
    self.pv.circuit_manager.user_callback_executor.submit(
  File "/home/prjemian/.conda/envs/bluesky_2022_3/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```
